apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: mkulyma/fireball
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8010

---
apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - port: 3000
      targetPort: 8010
